# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: npm test
      env:
        CI: true
        GCLA_CLIENT_ID: ${{ secrets.GCLA_CLIENT_ID }}
        GCLA_CLIENT_SECRET: ${{ secrets.GCLA_CLIENT_SECRET }}
        GCLA_USER_TOKEN: ${{ secrets.GCLA_USER_TOKEN }}
      run: |
        trap "rm user_token.json" EXIT
        echo "${GCLA_USER_TOKEN}" >user_token.json
        npm test >/dev/null
    - run: npm run semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
